### ISSUE TITLE
Allow semver version definition for unwantedRecommendations

### ISSUE THREAD

**Issue by Cyclodex** [Cyclodex/vscode-unwanted-recommendations#1]
After reading some comments, it seems that we are not progressing to get better support for defining extensions to recommend or not recommend.

https://github.com/microsoft/vscode/issues/138048#issuecomment-1440281726

There seems to be the need, that specific versions of extensions should be marked as unwantedRecommendation.
We could try to start with notification as this extension already does it, but adding support for semver in addition to the extension.

So with this feature, we could define a specific version or a semver version, which is not recommended to be installed.

1. This issue would be part 1 of the whole game, also because this was and is the main focus of this extension. Notifications.
2. However we maybe could go further and also support the `recommendations`, so instead of leaving it to VSCode only, we could also check the installed extensions and also support and verify specific semver versions on it. This would drastically improve the UX for some devs so it looks.
3. Further we could verify and check if there is the need, to also try to install these versions, if they are not installed or the semver does not match. But this needs to be checked and verified what is possible and how the UX should be done.

**Comment by Cyclodex** [comment]
Current progress, supports and notifies for defined semver versions.

However, because the `.vscode/extensions.json` does throw warnings if we do it in there, I introduced a new file `.vscode/extensionsVersionCheck.json` (actually every `.vscode/extensions*.json`) will be supported.

It allows to search for `^1.8` version ranges as per semver.
Or direct version matching `0.1.0`. If multiple versions of 1 extension should be marked, just make multiple entries of that package.


![image](https://github.com/Cyclodex/vscode-unwanted-recommendations/assets/840929/735c6b5c-de53-49fd-89ea-e26c1fb18c63)

**Comment by BananaAcid** [comment]
Is defining version numbers included in the published extension yet?

I can't seem to get it to trigger with @^2.6.2 ... without a version, it shows a dialog window.

**Comment by Cyclodex** [comment]
Unfortunately not...
I dont have extension publishing permission anymore, because i am not working for the same company anymore.
I have to check if i make a new extension, or if they allow me to transfer the extension to myself...

**Comment by Cyclodex** [comment]
We are progressing here, got permission to migrate extension.
The extensions is moving on to a new instance, because publisher can't be changed.

I will first release the exact same version but with a new name, before we start introducing the new semver feature, as I would like to make sure all is fine before we publish new release.

* old one: https://marketplace.visualstudio.com/items?itemName=GARAIOAG.garaio-vscode-unwanted-recommendations
* **NEW one**: https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions

Next step will be to deprecate the old one, in case of early adopters, feel free to already jump over to the new extension.

The new repo is located here: https://github.com/SoulcodeAgency/vscode-unwanted-extensions

**Comment by BananaAcid** [comment]
Wow, that is wonderful news!!!

**Comment by Cyclodex** [comment]
@BananaAcid what is your use case regarding the version number feature and how would it help you? Just to understand the situation better, thanks ;)

**Comment by BananaAcid** [comment]
There are extensions out there, that have changed either license or introduced a paywall. Or became incompatible with older projects by handling files/whatever differently. We do have all 3 cases. Using an older version and thereby the same in the student teams here where I teach (and additionally at the company where I work as well), is mandatory. Having it in the project config, would save me a lot of manual work.

**Comment by Cyclodex** [comment]
Ok.
Is it possible to mention a extensiond as a good example? Also defining
which version is the ok one and which is not ok, therefor unwanted.

We would need to test SemVer version definitions to then match the exact
versions you need

This information will help to provide a good use case and kind of a test
case.

Dont hesitate if you have multiple examples, it will help me further

thanks a lot

Nabil Redmann ***@***.***> schrieb am Fr., 5. Jan. 2024,
14:34:

**Comment by BananaAcid** [comment]
ThunderClient

like: https://github.com/rangav/thunder-client-support/releases

Install: https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

Version 2.6.2 was the last to not put "save config files to project" behind a paywall. --> https://github.com/rangav/thunder-client-support/blob/master/LICENSE.txt#L40-L41

https://github.com/rangav/thunder-client-support/commit/01013ec4c4461f2ce008c504e1101c3ca83a812c

https://github.com/rangav/thunder-client-support/compare/v2.6.1...v2.7.4#diff-d0ed4cc3fb70489fe51c7e0ac180cba2a7472124f9f9e9ae67b01a37fbd580b7


and somewhere was the license change ... before it was free for all, then subscription.

- The old projects still having all the config files, need the old versions to be able to look up something.

Btw: for the newer projects, we use FlashPost. (until that will be gone as well ;) )
---

I don't recall the extension names right now.

**Comment by Cyclodex** [comment]
@BananaAcid goooooood news here.

<img width="154" alt="image" src="https://github.com/Cyclodex/vscode-unwanted-extensions/assets/840929/ad3a0f99-d1d5-423f-95fc-67e5ad0323fc">

Check out the ["Unwanted Extensions"-extension](https://marketplace.visualstudio.com/items?itemName=Soulcode.vscode-unwanted-extensions). I just published a "pre-release" (1.1.1), where you should be able to create the mentioned file `.vscode/extensionsVersionCheck.json` and put the version numbers with your extension you want to block.

Insights:

<img width="1333" alt="image" src="https://github.com/Cyclodex/vscode-unwanted-extensions/assets/840929/191f3b20-bb5f-43d8-bc22-bfc748a89c35">

<img width="1052" alt="image" src="https://github.com/Cyclodex/vscode-unwanted-extensions/assets/840929/3e0ea0aa-4004-43bc-bd9d-69bd8605c1e0">

Please check the extension Description which should explain it all and has an example.

Let me know if it works for you, or if there are any issues with it.

If all is fine, I will make a public release, and close this ticket.

**Comment by Cyclodex** [comment]
Actually lets continue here please: https://github.com/SoulcodeAgency/vscode-unwanted-extensions/issues/2
